baseurl = "https://trunkbaseddevelopment.com/"
languageCode = "en-us"
title = "Trunk Based Development"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-24415524-3"

[params]
	# General information
	author = "paul-hammant"
	description = "A portal on this practice"
	copyright = "TrunkBasedDevelopment.com's contributors."

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/paul-hammant/tbd"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue"
    	accent  = "light-blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "paul-hammant"
	email   = "paul@hammant.org"

[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Context"
	url    = "context/"
	weight = 5

[[menu.main]]
	name   = "Five-minute overview"
	url    = "5-min-overview/"
	weight = 11

[[menu.main]]
	name   = "Deciding factors"
	url    = "deciding-factors/"
	weight = 21

[[menu.main]]
	name   = "Version control system features"
	url    = "vcs-features/"
	weight = 31

[[menu.main]]
	name   = "Version control system choices"
	url    = "vcs-choices/"
	weight = 32

[[menu.main]]
	name   = "Feature flags"
	url    = "feature-flags/"
	weight = 41

[[menu.main]]
	name   = "Branch by Abstraction"
	url    = "branch-by-abstraction/"
	weight = 53

[[menu.main]]
	name   = "Branch for release"
	url    = "branch-for-release/"
	weight = 55

[[menu.main]]
	name   = "Release from trunk"
	url    = "release-from-trunk/"
	weight = 56

[[menu.main]]
	name   = "Continuous Integration (CI)"
	url    = "continuous-integration/"
	weight = 61

[[menu.main]]
	name   = "Committing straight to the trunk"
	url    = "committing-straight-to-the-trunk/"
	weight = 62

[[menu.main]]
	name   = "Short Lived Feature Branches"
	url    = "short-lived-feature-branches/"
	weight = 63

[[menu.main]]
	name   = "Continuous Code Review"
	url    = "continuous-review/"
	weight = 65

[[menu.main]]
	name   = "Continuous Delivery (CD)"
	url    = "continuous-delivery/"
	weight = 71

[[menu.main]]
	name   = "Concurrent development of consecutive releases"
	url    = "concurrent-development-of-consecutive-releases/"
	weight = 75

[[menu.main]]
	name   = "Application strangulation"
	url    = "strangulation/"
	weight = 78

[[menu.main]]
	name   = "Observed habits"
	url    = "observed-habits/"
	weight = 81

[[menu.main]]
	name   = "You're doing it wrong"
	url    = "youre-doing-it-wrong/"
	weight = 91

[[menu.main]]
	name   = "Alternative branching models"
	url    = "alternative-branching-models/"
	weight = 101

[[menu.main]]
	name   = "Monorepos"
	url    = "monorepos/"
	weight = 111

[[menu.main]]
	name   = "Expanding Contracting Monorepos"
	url    = "expanding-contracting-monorepos/"
	weight = 112

[[menu.main]]
	name   = "Game Changers"
	url    = "game-changers/"
	weight = 121

[[menu.main]]
	name   = "Publications"
	url    = "publications/"
	weight = 131

[[menu.main]]
	name   = "Book on this topic"
	url    = "book/"
	weight = 132

[[menu.main]]
	name   = "Key to branch diagrams"
	url    = "key/"
	weight = 141

[[menu.main]]
	name   = "Contributions"
	url    = "contributions/"
	weight = 151

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"